### ISSUE TITLE
Id virtuals sind überflüssig

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server#100]
> Mongoose assigns each of your schemas an id virtual getter by default which returns the documents _id field cast to a string, or in the case of ObjectIds, its hexString. If you don't want an id getter added to your schema, you may disable it passing this option at schema construction time.

Hab ich ausprobiert, das geht auch ohne die virtuals explizit zu definieren.

**Comment by ddubbert** [comment]
dann können wir die weg machen beim rework der getter für ids

**Comment by ddubbert** [comment]
wurden entfernt
