### ISSUE TITLE
Recherche zu Frameworks

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#11]
Das Backend setzt auf Node.js als Grundlage und bietet diverse Frameworks zur Implementierungen für GraphQL und Sockets an. Eine erste Liste befindet sich im [Wiki](https://github.com/th-koeln/open-product-evaluation-server/wiki/Frameworks-und-Module).

**Comment by fdaugs** [comment]
Wir haben uns für graphql-yoga+mongodb entschieden.
