### ISSUE TITLE
Fehler, wenn keine Devices im Context sind.

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server#118]
Wenn keine Devices im Context sind, wird für das Feld nicht nur null zurrückgegeben, sondern es wird auch ein Fehler geworfen:

```json
{
	"data": {
		"context": {
			"name": "NewTestContext",
			"devices": null
		}
	},
	"errors": [{
		"message": "No devices found",
		"locations": [{
			"line": 4,
			"column": 5
		}],
		"path": [
			"context",
			"devices"
		]
	}]
}
```

**Comment by ddubbert** [comment]
ok das haben wir immer. auch wenn keine owner angegeben sind im device oder context etc. das liegt daran dass der fehler im model geworfen wird und nicht abgefangen. Hatten wir als debug erstmal drin und erstmal nicht als problem angesehen

**Comment by ddubbert** [comment]
also immer wenn über model.get eine entität gesucht aber nichts gefunden wird

**Comment by ddubbert** [comment]
also wir können überlegen ob wir das in den entity resolvern noch ändern aber denke nicht dass das die größte prio hat (falls halt noch andere sachen zu tun sind)

**Comment by fdaugs** [comment]
Ja auf gefallen war mir das jetzt auch nur, weil ich in den Tests unteranderem überprüfe, ob errors da sind und die Tests dann failen. Ich dachte erst, dasswäre ganz sinnvoll so, aber wenn es "gute" und "schlechte" Fehler gibt, wird das natürlich kompliziert.
