### ISSUE TITLE
Einzigartige Mail bei Profilupdate

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#124]
Sofern man sich einloggt, dann soll man auch seine eigenen Daten updaten können. Das läuft dann über die `updateUser` Mutation, allerdings bekomm ich dabei folgenden Fehler:

```json
{
  "data": null,
  "errors": [
    {
      "message": "Email already in use. Could not update user.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateUser"
      ]
    }
  ]
}
```

Ich schicke die bisherigen Daten einfach wieder mit, wenn sich nichts geändert hat. Dadurch spare ich mir das checken, ob sich was geändert hat. Es wäre praktisch, wenn das Backend nur prüft, ob ein anderer Eintrag die Mail hat und den eigenen Eintrag einfach ignoriert.

**Comment by slemke** [comment]
Das gleiche gilt natürlich auch für das Updaten eines anderen Nutzers als Admin.

**Comment by ddubbert** [comment]
zweiteres verstehe ich nicht? für admins haben wir doch gar keine mutation das muss über die datenbank gemacht werden. und macht es sinn seine eigene email einfach immer wieder auf den selben wert zu setzen? eig ja nicht also hatte ich da den eigenen user mit eingeschlossen
