### ISSUE TITLE
Dashboard Visualisierung im Backend

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#13]
Für die Ersteller der Umfragen und die Administratoren soll es ein einheitliches Userinterface geben, welches die Ergebnisse auf eine geeignete Weise visualisiert. Aktuell gibt es dazu noch folgende Themen:

* Welche Ergebnisse sollen visualisiert werden?
* Mit welchen Methoden sollen diese visualisiert werden?
* Werden dazu neue GraphQL Queries oder Mutationen benötigt?
* Welche Frameworks sollen dafür genutzt werden?
* Welche Kriterien sollen bei der Implementierung berücksichtigt werden?

**Comment by ddubbert** [comment]
#14

**Comment by slemke** [comment]
Diskussion verschoben: https://github.com/th-koeln/open-product-evaluation-server-admin/issues/1
