### ISSUE TITLE
' No devices found' bei Abfrage von Kontexten

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#130]
Bei der Abfrage von Kontexten bekomme ich folgenden Fehler:

```
ApolloError.js?7adc:43 Uncaught (in promise) Error: GraphQL error: No devices found
    at new ApolloError (ApolloError.js?7adc:43)
    at eval (QueryManager.js?8663:377)
    at eval (QueryManager.js?8663:809)
    at Array.forEach (<anonymous>)
    at eval (QueryManager.js?8663:808)
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (QueryManager.js?8663:801)
    at Object.next (QueryManager.js?8663:849)
    at notifySubscription (Observable.js?5234:126)
    at onNotify (Observable.js?5234:161)
```

Die dazugehörige Query:
```
query getContexts {
  contexts {
    owners{ id }
    id
    name
    // ...
    devices {id name owners { id firstName lastName } }
  }
}
```

Sollte in diese Fall der Wert von `context.devices` nicht `null` sein?

**Comment by fdaugs** [comment]
Ich glaube das ist related zu #118. Wenn du jetzt auch Probleme damit hast, werden wir dass wohl fixen müssen. Das Ding ist, dass wir immer alle "Fehler" in die Anwort packen, selbst wenn null erlaubt ist.

**Comment by slemke** [comment]
>  Das Ding ist, dass wir immer alle "Fehler" in die Anwort packen, selbst wenn null erlaubt ist.

Das ist hier halt problematisch (wie du selbst schon sagst: "Fehler"). Ein Kontext ohne Device ist halt ein absolut valider Zustand und sollte daher auch keine Fehler werfen.

**Comment by tolja** [comment]
gleiches problem hab ich auch im testclient. wenn ich von allen kontexten die devices anzeigen will und keine devices vorhanden sind wirft mir vue den fehler

**Comment by fdaugs** [comment]
Also der quick and drity fix wäre einfach statt dem error einfach in den models ein leeres Array zu returnen. Null returnen geht nicht, weil es teileweise abfragen nach der length und so gibt.

**Comment by slemke** [comment]
Mir ist auch gerade aufgefallen das sich `getContext` und `getContexts` unterschiedlich verhalten. Bei `getContext` bekomme ich die `devices` ohne Probleme, wenn ich alle Kontexte haben will, dann nicht.

**Comment by fdaugs** [comment]
Das dürfe eigentlich keinen Unterschied machen. Bei mir ist da auch keiner. In beiden Fällen bekomme ich die Fehler.

**Comment by slemke** [comment]
Mein Fehler, der Kontext hatte doch Devices. Läuft beides nicht.

**Comment by ddubbert** [comment]
ne also wenn man das fixed dann in den entity resolvern. aber das ist eig kein großes ding. da kann ich mich morgen zur not dran setzen oder evtl heute noch.

**Comment by ddubbert** [comment]
und was das andere betrifft: du darfst natürlich nicht alle Devices sehen die in dem Context drin sind wenn sie dich nicht als owner deklariert haben. Das kann ich ändern war aber erstmal so angedacht. man könnte das so abändern dass du sie sehen darfst aber nicht bearbeiten

**Comment by tolja** [comment]
also das mit den devices passt bei mir jetzt
