### ISSUE TITLE
ChoiceQuestion default Wert, aber null erlaubt?

### ISSUE THREAD

**Issue by tolja** [th-koeln/open-product-evaluation-server#131]
Bei der ChoiceQuestion gibt es einerseits die Möglichkeit einen default Wert zu setzen und damit eine Choice vorauszuwählen, aber andererseits darf die choice selbst auch null sein. Das ist so aber im Client nicht umzusetzen. Wenn ich eine Antwort vorauswähle, wird ja immer die ID dieser Antwort geschickt auch wenn der Befragte jetzt keine Antwort geben möchte (außer es gibt noch die Möglichkeit mit einem "Antwort nicht geben" Button, aber ich denke es wäre besser dann einfach gar nichts vorzuwählen

**Comment by slemke** [comment]
Default Wert: `A`
- [x] A
- [ ] B
- [ ] C

Default Wert: `null` oder `''`
- [ ] A
- [ ] B
- [ ] C

Absenden der Anfrage:
- Mit Auswahl: dann die ID
- Keine Auswahl oder überspringen: ohne ID (entweder "überspringen" Button oder abwählen

**Comment by tolja** [comment]
Ja es geht hier darum dass wenn ich per graphql eine Abfrage mache und dort bei meiner choiceQuestion ein default wert festgelegt ist (z.b. die id von antwort 1). dann ist zumindest bei mir der radio button dieser antwort vorausgewählt und würde dann auch als antwort abgeschickt werden wenn man zur nächsten frage geht. wenn ich keine antwort vorauswähle, dann wird auch entsprechend "null" gesendet

**Comment by tolja** [comment]
Achso ich glaub ich hab einfach die Choice Question falsch verstanden. Also es dürfen auch mehrere Antworten geschickt werden? Dann wäre das erledigt. Dachte bis jetzt dass nur eine Antwort geschickt wird

**Comment by slemke** [comment]
Nein, du schickst eine Antwort pro Frage. Diese kann aber leer sein um zu kommunizieren, das du diese Frage übersprungen hast.

Der Rest sind alles Fragen die Abhängig von der Implementierung sind. Mit dem normalen Verhalten von Radiobuttons in HTML kommst du nicht weiter, das ist klar. Das musst du dann entsprechend umsetzen. Die ChoiceQuestion ist soweit korrekt.

**Comment by tolja** [comment]
Ja okay es wäre easy das ganze mit Select Buttons zu lösen aber ich dachte mit Radios ist es für diejenigen einfacher, die dann die Umfrage beantworten. Also wenn ansonsten alles passt kann hier zugemacht werden

**Comment by slemke** [comment]
Du kannst das ganze auch problemlos mit Radio Buttons und ein paar Zeilen Javascript implementieren. Google mal nach "deselect radio button" und du bekommst sofort eine stackoverflow antwort, welche sagt wie das geht.

**Comment by tolja** [comment]
Ja klar kann ich den Radio Button per Code deselecten aber dann kann ich ja auch gleich null und keine default Antwort mitsenden. Mit den Select Buttons will ich ja demjenigen, der die Umfrage beantwortet, erlauben, die default value zu deselecten und dann eine leere Antwort zu senden. Klar kann man auch Radio Buttons deselecten aber durch den Klick auf den Button ist das bei Radios eigentlich nicht üblich

**Comment by slemke** [comment]
Checkboxen gehen dann aber auch nicht, da diese mehrere Antworten erlauben. Du kannst doch auch einfach einen zusätzlichen Radiobutton hinzufügen mit "Keine Antwort" (value = null). Alles in allem kein Problem der ChoiceQuestion.

**Comment by ddubbert** [comment]
naja wenn der Fragenersteller eine default choice haben will dann kann er sie festlegen. wenn nicht dann soll halt null gegeben werden

**Comment by ddubbert** [comment]
und ja letzteres von sascha finde ich auch ok

**Comment by tolja** [comment]
Ja das wäre die billigste Lösung mit dem Button "Keine Antwort", das hab ich z.B. bei der RankingQuestion so gemacht weil ich mit vuedraggable eine Sortierung erlaube aber wenn man keine Sortierung durchführt soll das nicht heißen, dass man die Sortierung des Arrays als Antwort senden will sondern null
