### ISSUE TITLE
Implementierung der Adminview

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#14]
Um die Umfragen verwalten zu können soll ein entsprechendes Userinterface implementiert werden. Hier sind aktuell noch folgende Themen offen:

* Welche Funktionen sollen implementiert werden?
* Welche Frameworks sollen genutzt werden?
* Nach welchen Methodologien soll vorgegangen werden?
* Sollen Tests für das Frontend implementiert werden? (und wer übernimmt die)

**Comment by fdaugs** [comment]
Also ich halte Webtest für sinnvoll (selenium, puppeteer). Und das ganze natürlich automatisiert.

**Comment by slemke** [comment]
Komplett ausgelagert: https://github.com/th-koeln/open-product-evaluation-server-admin
