### ISSUE TITLE
Frontend als fester Bestandteil des "Backend Servers"

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#141]
Zum aktuellen Zeitpunkt gibt es nichts, was gegen eine feste Integration des Adminview im Backend spricht. Die Trennung zwischen Backend und Adminview Repository hat über die "Projekt - Entwicklung" nur Nachteile mit sich gebracht (kaum Reviewprozess, zwei Orte für Code, zwei Orte für Dokumentation). Zu Beginn der Evaluation sollte sich Gedanken darüber gemacht wo das Adminview auf Dauer bleibt und wie mit den Webclients umgegangen wird (siehe dazu #46)

**Comment by tolja** [comment]
Dazu hätte ich noch die Anregung die Sachen von melnem Demo-Client evtl. direkt als Previews in die Erstellung von Questions zu integrieren
