### ISSUE TITLE
Anforderungen an die Frontend Teams

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#15]
Um unnötige Abstimmungsschwierigkeiten mit den Frontend Teams zu vermeiden sollte eine entsprechende Liste existieren, welche klar definiert was es zu implementieren gilt und welche Schnittstellen sie benutzen können um ihre Ziele zu erreichen.

**Comment by fdaugs** [comment]
Related to #21

**Comment by ddubbert** [comment]
Habe eine vorläufige und recht ausführliche Anleitung zur Nutzung der API erstellt und hiervon eine PDF in den Sciebo-Ordner "Architektur" geladen. In der Anleitung werden zunächst die Bestandteile der Architektur nochmal genau erläutert und anschließend der Workflow für jeweils einen Survey Controller und ein Evaluation Device beschrieben. Ist zwar 7 Seiten lang jedoch sicherlich noch unvollständig. Schaut sie euch mal an und wir diskutieren Mittwoch darüber.

**Comment by slemke** [comment]
https://github.com/th-koeln/open-product-evaluation-server/wiki/Anleitung
