### ISSUE TITLE
Authentifizierung / Authorisierung

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#17]
Zu diesem Thema gibt es noch die folgenden Themen:

* Muss sich jede Komponente authentifizieren?
* Oder gilt dies nur für Komponenten, welche mit dem User interagieren?
* Passen [JSON Web Token](https://jwt.io/) noch in diesen Kontext?
* Welche Rollen existieren im System?
* Welche Rechte haben diese Rollen?

**Comment by slemke** [comment]
Diskussionsbeitrag für den 01.06.:

**Muss sich jede Komponente authentifizieren?**

Grundsätzlich sollte man zwischen zwei Arten von Umfragen unterscheiden:

* Umfragen, welche für alle zugänglich sind
* Umfragen, welche nur für bestimmte Komponenten erlaubt sind

Jede Komponente registriert sich über den GraphQL Endpunkt und kann daraufhin Informationen erhalten. Bei der Registrierung wird ein JSON Web Token zurückgeben, welches die Informationen der Komponente als Payload enthält und bei Bedarf im Frontend dekodiert werden kann. Das Backend entscheidet, basierend auf dem JWT, welche Informationen das Device erhält.

Das bedeutetet allerdings, dass JWT für User als auch für Systemkomponenten vergeben werden. Lediglich der Payload des Tokens variiert dabei.

**Gilt das nur für Komponenten, welche sich authentifizieren?**

Da sich jede Komponente authentifiziert, erübrigt sich die Frage.

**Passen JSON Web Token in den Kontext?**

Siehe oben.

**Welche Rollen existieren im System?**

Um die Verwaltung der Rechte „einfach" zu halten sollten zwei Rollen existieren:

* Administratoren
* User (Ersteller der Umfragen)

Der Unterschied ist das Administratoren über alle Rechte verfügen, die User allerdings nur die für sie relevanten Umfragen und deren Daten sehen und bearbeiten können.

**Welche Rechte haben diese Rollen?**

User:
* Erstellen, Bearbeiten und Löschen der eigenen Umfragen und deren Daten
* Uploaden / Löschen von Bildern, welche zu den eigenen Umfragen gehören
* Registrieren und Anmelden

Administratoren:
* Alle Rechte der User
* Verwaltung und Zuordnung der Controller
* Verwaltung und Zuordnung der Devices
* Verwaltung der User(-daten / -rechte)

**Comment by fdaugs** [comment]
Theoretisch könnte man doch auch die User role im payload des jwt speichern, oder?

**Comment by slemke** [comment]
User JWT:

* userID
* Rolle

Device / Controller:

* Device ID  / Controller ID
