### ISSUE TITLE
Kriterien für Pull Requests

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#20]
Es sollte eine Liste für die Kriterien bei Pull Requests geben, damit sich die Reviews schnell abarbeiten lassen.

**Comment by fdaugs** [comment]
Das könnte man ja teilweise automatisieren: 
Also eslint und min. unit test. [Beispiel](https://medium.freecodecamp.org/how-to-stop-errors-before-they-ever-hit-your-codebase-with-travis-ci-and-eslint-7a5a6b1fcd4a)

**Comment by slemke** [comment]
Vorläufige Gedanken / Liste vom 30.06.:

* Entwurfsmuster
* Bezeichnung (Variablen, Funktionsnamen, ... )
* Strukturelemente (Callbacks / Promises / await, Objektstrukturen, ... )

**Comment by fdaugs** [comment]
Was haltet ihr von Issue/ Pull Request templates? [Hier](https://embeddedartistry.com/blog/2017/8/4/a-github-pull-request-template-for-your-projects?format=amp) ist besonders der letzte Teil als Checkliste interessant. Da könnte man das von dir reinschreiben. Wir müssten dann auch vorgeben, was und wie getestet werden muss.

**Comment by slemke** [comment]
Neue Liste für Kriterien (andere Inhalte werden spontan bewertet):

* Entwurfsmuster
* Variablennamen
* Funktionsnamen
* Lesbarkeit
* Code Länge
* Übersichtlichkeit
* Dateinamen
* Promises / await
* ECMA 6
