### ISSUE TITLE
Travis CI Setup

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server#22]
- [x] Initiales Setup.
- [x] Unit Test.
- [x] ESLint.
- [x] So configurieren, dass nur bei einem Pull-Request alles getested wird.

**Comment by slemke** [comment]
Ich hab es erstmal bei GraphQL untergebracht, damit wir die Todos fürs Konzept durcharbeiten können. Die Diskussion, ob wir Travis nutzen und in welcher Form wollten wir nächste Woche führen.
