### ISSUE TITLE
Probleme beim Programmeiren

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server#24]
* password bei user fehlt in database schema
* UserCreatePayload funktioniert nicht "out of the box -> Warum geau soll da ein token returned werden? Das ist doch für den admin oder? Ansonsten eher login.
* Ich habe _id in id umbenannt, da sonst nicht automatisch vergeben + keine unterschiedlichen Feldnamen zwischen database und api schema möglich
* Ähnlich mit createtAt und updatetAt -> Das muss überall gleich heißen, sonst fehler...
* Da sind noch viele inkonsistenzen wie bspw. creationDate?!

**Comment by slemke** [comment]
Merged #7
