### ISSUE TITLE
Datenbankstruktur

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#25]
Für die Implementierung des Backends müssen wir noch Punkte zu den Datenstrukturen in der MongoDB klären:

1. Welche Entitäten sind auch Collections?
2. Wollen wir Referenzen nutzen oder speichern wir redundant?
3. Sollen die Strukturen möglichst den GraphQL Definitionen gleichen? Falls nicht, wie konstruieren wir die korrekten Objekte in den Resolvern?

Frage 1 und 2 hängen natürlich irgendwo voneinander ab. Die Frage wird in der ersten Version des Database Seeding deutlich #23 :

```json
{
    "_id" : "6d1cce661176943b363983cd",
    "creationDate" : "2018-06-17T16:15:40.315Z",
    "lastUpdate" : "2018-06-17T16:15:40.315Z",
    "creator" : "b3daa77b4c04a9551b8781d0",
    "title" : "Untersuchung zum Verhalten von Informatikern in Hochschulen",
    "description" : "Eine wissenschaftliche Umfrage mit der Forschungsfrage: \"Wie verhalten sich Informatiker?",
    "isPublic" : true,
    "types" : [ 
        "CHOICE", 
        "REGULATOR", 
        "LIKE"
    ],
    "questions" : [ 
        "9cae9b11d0c6db0cac09329c", 
        "96c0cd620daff8354281320d", 
        "a882013a2f55796865e40937", 
        "44917b5d9b18cfe4ffe57ead"
    ],
    "votes" : [ 
        "4480f1f18e8a9a94b58e6fc7"
    ],
    "contexts" : [ 
        "a966820c8e80d44b7f846b72"
    ],
    "images" : [ 
        "ff7e5bb3b65ed9d886318cf2", 
        "047b9248e8a75efddb8a9c4d"
    ]
}
```

**Comment by ddubbert** [comment]
Grundsätzlich würde ich allem was eine is besitzt und alleine stehen kann eine Collection zuweisen. Also : Survey, Context, Device, User . Die anderen Komponenten (question, vote) sind ja eigentlich abhängig von der survey und könnten dementsprechend direkt in dem Objekt gespeichert werden (ohne eigene Collection). Allerdings haben wir die ja auch so modelliert, dass sie in einer eigenständigen Collection stehen könnten, sodass wir dann nochmal Anpassungen machen müssten/sollten (Referenzen zur Survey löschen) falls wir Ihnen doch keine eigene Collection zuweisen. Images sind da so ein Mittelding. Einerseits werden sie gesondert hochgeladen und wir wollen dopplungen vermeiden, andererseits gehören auch sie direkt zu einer Survey und könnten lediglich darin gespeichert werden. Ich denke gesonderte collections vereinfachen queries aber die Speicherung in den Objekten würde die Datenbankzugriffe reduzieren. Dann müssen wir aber auch nochmal die graphql queries angucken und ggf. überarbeiten (kann die gerade nicht auf mache )

**Comment by ddubbert** [comment]
Oh würde die aber glaube ich in einzelne collections packen weil:
- bessere Aufspaltung der Arbeitsbereiche (in unserer Gruppe)
- verschachtelte queries in Mongodb können Probleme bereiten (sind nicht sonderlich angenehm). Somit können einzelne Elemente leichter gesucht / zurückgegeben werden
- Änderungen an den Elementen sind einfacher

Der Nachteil ist natürlich dass wir so um einiges mehr Aufrufe haben , was jedoch ggf. nicht so schlimm ausfällt, weil bei graphql ja nicht immer jedes Attribut angefragt wird
