### ISSUE TITLE
EsLint Rule Unix Linebreaks

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server#27]
Wollen wir die eslint Regel [hier](https://github.com/th-koeln/open-product-evaluation-server/blob/master/.eslintrc.json#L15-L18) beibehalten? Github konvertiert bei die eols zu CRLF und EsLint wirft dann Fehler:
`1:13   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`

Wollen wir konsitent auf LF arbeiten oder die Regel verwerfen? Wenn wir uns für ersteres entscheiden, müssent wir nen .gitattributes anlegen, dass das entsprechend festlegt.

**Comment by fdaugs** [comment]
Git konvertiert im Automodus die LF Endings auf Windows zu CR LF und da es die Regel gibt, dass diese LF sein müsse, führt das dann zu Fehlern. Ich weiß übrigens nicht, ob git die dann beim pushen wieder zurück konvertiert, aber ich denke wir sollten da iwie einheitlich bleiben, oder?

**Comment by slemke** [comment]
Von dem Link oben:

> Git can handle this by auto-converting CRLF line endings into LF when you add a file to the index, and vice versa when it checks out code onto your filesystem. You can turn on this functionality with the core.autocrlf setting. If you’re on a Windows machine, set it to true — this converts LF endings into CRLF when you check out code:
>
> `$ git config --global core.autocrlf true`

Damit konvertiert er jedes mal CRLF in LF, wenn du eine Datei zum Index hinzufügst. Damit das ganze bei dir auch im Editor (War VS?) funktioniert einfach folgendes [ändern](https://code.visualstudio.com/docs/getstarted/settings#_settings-and-security):

```
  // The default end of line character. Use \n for LF and \r\n for CRLF.
  "files.eol": "\r\n", 
```
Da gibst du dann nur `\n` und ESLint gibt auch keine Fehler.
