### ISSUE TITLE
Standard-Icons für Like, Dislike..

### ISSUE THREAD

**Issue by tolja** [th-koeln/open-product-evaluation-server#30]
Finde es bedenklich die Standard-Bilder für einen Like-Button, Dislike-Button usw. von irgendwelchen Seiten zu verlinken. Wie sieht es da mit Lizenzen aus? Wenn wir das System öffentlich machen muss klar sein, welche Nutzungsrechte wir an den Bildern haben. Entweder Bilder mit CC0 Lizenz verwenden oder die Lizenz der bisher verlinkten Bilder klären. 

Das gilt auch wenn es nur für die Seeds ist, die werden ja auch von den Frontend-Teams verwendet und sind somit öffentlich.

**Comment by slemke** [comment]
Seh ich auch so, da bin ich sauber dran vorbei gescrollt. Eigentlich sollte da nur die relative URL auf unsere static files rein.

**Comment by fdaugs** [comment]
Die Bilder müsste ja das Frontend laden und das kommt doch ohne CORS da eh nicht dran, oder?
