### ISSUE TITLE
Context in GraphQL implementieren

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#31]
Implementierung der `context` Entität in GraphQL:
- [x] Implementierung des Mongoose Schema
- [x] Implementierung des Models
- [x] Implementierung der Resolver
  - Queries:
    - [x] Contexts
    - [x] Context
  - Mutation
    - [x] createContext
    - [x] updateContext
    - [x] deleteContext
- [ ] Tests

**Comment by ddubbert** [comment]
Erster Prototyp fertig gestellt und in den dev Branche gepushed
