### ISSUE TITLE
Device in GraphQL implementieren

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#32]
Implementierung der `device` Entität in GraphQL:
- [x] Implementierung des Mongoose Schema
- [x] Implementierung des Models
- [x] Implementierung der Resolver
  - Queries:
    - [x] Devices
    - [x] Device
  - Mutation
    - [x] createDevice
    - [x] updateDevice
    - [x] deleteDevice
- [ ] Tests

**Comment by ddubbert** [comment]
Erster Prototyp fertig gestellt und in den dev Branche gepushed
