### ISSUE TITLE
Image in GraphQL implementieren

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#33]
Implementierung der `image` Entität in GraphQL:
- [x] Implementierung des Mongoose Schema
- [x] Implementierung des Models
- [x] Implementierung der Resolver
  - Mutation
    - [x] createImage
    - [x] updateImage
    - [x] deleteImage
- [ ] Tests

**Comment by ddubbert** [comment]
Erster Prototyp fertig gestellt und in den dev Branche gepushed
