### ISSUE TITLE
Question in GraphQL implementieren

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#34]
Implementierung der `question` Entität in GraphQL:
- [x] Implementierung des Mongoose Schema
- [x] Implementierung des Models
- [x] Implementierung der Resolver
  - Mutation
    - Like Questions
      - [x] createLikeQuestion
      - [x] updateLikeQuestion
    - Like Dislike Questions
      - [x] createLikeDislikeQuestion
      - [x] updateLikeDislikeQuestion
    - Choice Questions
      - [x] createChoiceQuestion
      - [x] updateChoiceQuestion
    - Regulator Questions
      - [x] createRegulatorQuestion
      - [x] updateRegulatorQuestion
    - Ranking Questions
      - [x] createRankingQuestion
      - [x] updateRankingQuestion
    - Ranking Questions
      - [x] createFavoriteQuestion
      - [x] updateFavoriteQuestion
    - [x] deleteQuestion

**Comment by ddubbert** [comment]
Erster Prototyp fertig gestellt und in den dev Branche gepushed
