### ISSUE TITLE
State in GraphQL implementieren

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#35]
Implementierung der `state` Entität in GraphQL:
- [x] Implementierung des Mongoose Schema
- [x] Implementierung des Models
- [x] Implementierung der Resolver
  - Queries:
    - [x] state
  - Mutation
    - [x] createState
    - [x] updateState
    - [x] deleteState

**Comment by ddubbert** [comment]
Erster Prototyp fertig gestellt und in den dev Branche gepushed
