### ISSUE TITLE
Survey in GraphQL implementieren

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#36]
Implementierung der `survey` Entität in GraphQL:
- [x] Implementierung des Mongoose Schema
- [x] Implementierung des Models
- [x] Implementierung der Resolver
  - Queries:
    - [x] Surveys
    - [x] Survey
  - Mutation
    - [x] createSurvey
    - [x] updateSurvey
    - [x] deleteSurvey

**Comment by ddubbert** [comment]
Erster Prototyp fertig gestellt und in den dev Branche gepushed
