### ISSUE TITLE
User in GraphQL implementieren

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#37]
Implementierung der `user` Entität in GraphQL:
- [x] Implementierung des Mongoose Schema
- [x] Implementierung des Models
- [x] Implementierung der Resolver
  - Queries:
    - [x] Users
    - [x] User
  - Mutation
    - [x] createUser
    - [x] updateUser
    - [x] deleteUser
    - [x] login

**Comment by ddubbert** [comment]
Erster Prototyp fertig gestellt und in den dev Branche gepushed
