### ISSUE TITLE
Branchmodell

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server#47]
Wie strukturieren wir unsere Branches? 
Ich stelle mal folgendes zur Diskussion: 

https://nvie.com/posts/a-successful-git-branching-model/

**Comment by slemke** [comment]
Das ist das Modell, welches ich mit `integration`-Branch meinte. Bin dafür und würde das auch für das Adminview Repository übernehmen, sofern wir das übernehmen.

**Comment by fdaugs** [comment]
Wir machen das ja jetzt so.
