### ISSUE TITLE
Nested Array: Votes und Questions

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server#51]
Wir hatten ja gesagt, dass votes und questions keine eigenen collections. Allerdings hat sich jetzt gezeigt, dass sich so nested arrays nicht so gut managen lassen als wenn sie in eigenen Collections wären. Was meint ihr dazu?

**Comment by ddubbert** [comment]
Wichtig zu erwähnen: mit mongoose Population können Referenzen schon auf datenbankebene gut aufgelöst werden weiterhin würden die einzelnen Entity-Ordner teilweise überflüssig da ein vote auch auf das Survey Model zugreifen würde (gleiches für Image und question). Das Problem der nested arrays ist zudem vor allem bei questions der Fall (Hierarchie: Survey -> [question] -> [items] -> Image z.b)

**Comment by slemke** [comment]
Wo hat sich Was gezeigt? Wie bei dem anderen Issue fehlt auch hier ein Beispiel / Code. 

Was die Mongoose Population angeht: Was genau ist hier das Problem? Den Fall das man mehre Ebenen durchlaufen muss?

**Comment by fdaugs** [comment]
approved
