### ISSUE TITLE
id wird in _id umbenannt

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server#52]
Um den key, der aus der mongo kommt nicht umbenennen zu müssen wird das Graphql-Schema entsprechend angepasst.

**Comment by ddubbert** [comment]
Hier spielen die nested keys vorwiegend eine Rolle. So müsste man für eine Ausgabe erst alle Ebenen eines Objektes durchlaufen und rekursiv die id austauschen

**Comment by slemke** [comment]
Das Thema hatten wir ja schon während der Meetings. Man gibt keine Implementierungsdetails durch eine Schnittstelle nach außen. Das dies zusätzliche Arbeit durch das Mapping der IDs erfordert ist normal. Ohne vernünftiges Beispiel bietet das hier eh keine gute Grundlage für eine Diskussion. Abgesehen davon bin ich in jedem Fall dagegen, da solche Änderungen im nach hinein nicht so einfach zu machen sind.

**Comment by ddubbert** [comment]
not approved
