### ISSUE TITLE
Hash MongoDB ID's

### ISSUE THREAD

**Issue by ddubbert** [th-koeln/open-product-evaluation-server#56]
Um keine implementierungs-Details an den Client zu schicken, sollten die mongoDB ID's vor dem Response gehashed und bei einer Anfrage wieder der ursprünglichen ID zugeordnet werden. Hierbei sollte zunächst ein Platzhalter implementiert werden, welcher nach dem ersten Prototypen ausdefiniert wird. So kann dieser schon im Prototyp-Code eingebunden / genutzt werden.

**Comment by fdaugs** [comment]
Implementiert in #59, #60 und #61
