### ISSUE TITLE
Atomic Database Modifications

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server#62]
Um den Bedarf von Transactions zu vermeiden (in mongo eh nicht einfach möglich), werden Referenzen aus den Objekten in GraphQL aufglöst, aber keine bidirektionalen multi-referenzen mehr in der db gehalten. 
Bsp:

Survey:{
id: 2
contexts: [1,2,3] <- nicht benötigt. Wird durch query in context collection aufgelöst.
}

Context:{
id: 1
activeSurvey: SurveyID
}

Anpassung im Mongoose Shema

- [x] context: keine referenz zu Devices mehr
- [x] question: surveyId hinzufügen  
- [x] survey: keine referenz zu votes und contexts, questionsArray nur als Reihenfolge nicht als Relation
- [x] vote benötigt Survey Referenz

**Comment by ddubbert** [comment]
wurde insgesamt umgesetzt
