### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server#67]
Wir sollten (besonders beim Login mit email) dafür sorgen, dass das nicht case sensetive ist:

Bsp: 
*In DB:* Jake@doe.com

*Query:* Jake@doe.com *valid*
*Query:* jake@doe.com *error*

**Comment by ddubbert** [comment]
kann ich anpassen

**Comment by ddubbert** [comment]
wurde gefixed in cb7971ef667d15c49be324a01b1e16b0083871c3
