### ISSUE TITLE
Update und Delete where Query

### ISSUE THREAD

**Issue by ddubbert** [th-koeln/open-product-evaluation-server#70]
Bisher hatten wir in den update- und delete-Methoden lediglich die Möglichkeit eine ID anzugeben und ein einzelnes Objekt zu verändern. Jetzt soll die ID durch eine where-query ersetzt werden um eine größere Varietät von Zugriffen zu ermöglichen.

- [x] User
- [x] Survey
- [x] Question
- [x] Image
- [x] Context
- [x] Device
- [x] Vote

**Comment by slemke** [comment]
Was wäre da ein Beispiel?

**Comment by fdaugs** [comment]
beim Löschen einer Survey muss aus allen Contexten die die gelöschte servey als active survey haben, activeSurvey auf null gesetzt werden

**Comment by ddubbert** [comment]
Beim löschen einer survey müssen alle questions gelöscht werden die die survey referenzieren

**Comment by ddubbert** [comment]
Wurde überall implementiert
