### ISSUE TITLE
Delete return Werte nicht mehr das gelöschte Objekt

### ISSUE THREAD

**Issue by ddubbert** [th-koeln/open-product-evaluation-server#71]
Wir haben in der GraphQL-Schnittstelle definiert, dass bei jedem delete das gelöschte Objekt zurückgegeben wird. Das geht so leider nicht (wenn wir die Objekte löschen können die Attribut-Resolver nicht mehr auf das Objekt in der DB zugreifen, sodass wir das Objekt nicht rekonstruieren können), sodass ich vorschlage stattdessen einfach Auskunft darüber zu geben ob es gelöscht wurde.

Also z.B.:
deletePayload {
    success: Boolean!
}

**Comment by fdaugs** [comment]
ok

**Comment by slemke** [comment]
Warum wird im Resolver nicht erst ein `get` durchgeführt bzw im Model einfach das Objekt als return value von `delete` definiert? Dann hättet ihr doch das Objekt?

**Comment by fdaugs** [comment]
Das Problem ist, dass die resolver rekursiv aufgerufen werden.

**Comment by ddubbert** [comment]
naja die Atrribut resolver der Entities werden aufgerufen nachdem die mutation oder query stattgefunden hat. dementsprechend werden die danach aufgerufen

**Comment by ddubbert** [comment]
Beispiel:
Query: {
    getSurvey: async (parent, args, context, info) => {
        return await surveyDB.get({survey query})
    }
},
Survey: {
    questions: async (parent, args, context, info) => {
        return await questionDB.get({survey: parent._id})
    }
}

Typischer Ablauf:
Die Query getSurvey wird aufgerufen, holt sich die Daten aus der DB. Dabei sind die questions und andere entities noch nicht drin weil diese in eigenständigen Collections gehalten werden. Nun wird der Output dieser query intern von GraphQL-Yoga an die zuständigen Attribut-Resolver der Survey weitergeleitet (an die die vom Client angefragt wurden). Hier kann man auf das Vater-Objekt (Output der Query) zugreifen und anhand der darin enthaltenen ID die zugehörigen Fragen aus der Datenbank ziehen. Dieser Output würde dann wiederum an die Attribut-Resolver der Question geleitet werden, wo sie wiederum ausgewertet / ergänzt werden. 

So ist das bei jedem Attribut, was noch einmal speziell in den Resolvern aufgelistet wird. Daher kann man beim Delete das Objekt nicht zurückgeben, außer man würde erstmal in der ersten Query alle daten sammeln und in jedem Attribut resolver dann gucken ob die Daten vorhanden sind oder nicht und dann entscheiden ob man diese nochmal Suchen muss oder einfach aus dem Vater nimmt (was aber dem Sinn von GraphQL wiederspricht)

**Comment by ddubbert** [comment]
wobei success als Rückgabe eigentlich doppelt gemoppelt ist, da ein Fehler geworfen wird wenn es nicht funktioniert oder keine Rechte da sind. Mehr Sinn würde ja machen die IDs der gelöschten Dokumente raus zu geben aber die werden von Mongoose nicht raus gegeben.

**Comment by slemke** [comment]
Okay, ich verstehe warum das an die entsprechenden Resolver muss. Das würde doch dann nur für die Query gelten? Aber eine `delete` wäre doch eine Mutation, bei der man diese Daten abfragen und zurück geben kann? Ich hab dann doch einfach sowas wie:

```js
  deleteQuestion(parent, args, context info) {
    let survey = await surveymodel.get(...);
    surveymodel.delete(id)
    return survey;
  }
````

**Comment by fdaugs** [comment]
Zugegebenermaßen sieht es so aus, als könntest du Recht haben. #

**Comment by ddubbert** [comment]
nicht ganz. Das zählt auch für mutations. Da muss der rückgabewert ja auch immer über die attribute-resolver vervollständigt werden weil innerhalb des Payloads ja auch wieder beispielsweise eine survey ist. Wie gesagt. man müsste ansonsten erst die survey in der mutation raus holen. dann daraus die werte nehmen und weitere db zugriffe für die unterobjekte machen. also genau das was die attribut-resolver machen nur in der mutation selber.

**Comment by ddubbert** [comment]
und dann müsste man in den resolvern immer erst gucken ob schon ein richtiger wert in dem attribut steht oder ob dieser erst noch geholt werden muss.

**Comment by ddubbert** [comment]
Hier müssen wir uns langsam auf einen gemeinsamen Nenner einigen

**Comment by fdaugs** [comment]
Beschlossen:

deletePayload {
    success: Boolean!
}
