### ISSUE TITLE
Modellierung der Socketverbindung

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#8]
Um Änderungen der Daten und verschiedene Updates asynchron an den Client kommunizieren zu können sollen entsprechende Socktverbindungen implementiert werden. Dafür müssen noch folgende Dinge erledigt werden:

- [x] Definition der Socktverbindung
- [x] Modellierung des Payloads
- [x] Softwarerecherche

**Comment by ddubbert** [comment]
Können wir das Issue nicht schließen weil wir uns ja für Yoga entschieden haben und dementsprechend das Subscription-Modul davon nutzen?
