### ISSUE TITLE
Entitäten wie Items, Labels und Co mit Ids versehen

### ISSUE THREAD

**Issue by slemke** [th-koeln/open-product-evaluation-server#98]
Wir sollten nochmal überlegen, ob wir Elemente ohne IDs (wie bspw. Items oder Labels) doch mit IDs versehen. Ursprünglich war die Aussage das wir das nicht brauchen, da die Sortierung durch den Platz innerhalb des Arrays gegeben ist und wir die Elemente als Ganzes bearbeiten.

Das klappt leider in Vue.js nicht wirklich. Allein um die Elemente anzuzeigen verlangt Vue einen Index um die Inhalte korrekt darstellen zu können. Derzeit habe ich dort den eigentlichen Wert (bspw. der Name bei einem Label) angegeben. Dies führt aber dazu das leere Elemente die gleiche ID haben. Sollte ich nun ein leeres Label löschen, werden alle leeren Label gelöscht. Dies gilt auch für Labels oder Items mit dem gleichen Namen.

**Comment by fdaugs** [comment]
Reicht das nicht, wenn du den index des Arrays als ID angibst?

**Comment by ddubbert** [comment]
In diesem Kontext wurden ein paar Sachen geplant:
- items, labels und choices erhalten ids, jeweils create, update und delete resolver
- questions werden nun nur mit value, description und type angelegt
- über das update einer question können alle Attribute abgesehen von items, labels und choices verändert werden (keine unterschiedlichen Aufrufe pro QuestionType mehr)
- zu den items, labels und choices gehörende Bilder werden nun direkt in deren Updateresolvern hochgeladen (ähnliches gilt für likeImage und dislikeImage innerhalb der update Question)

So wird auch hier das Erstellungsschema beibehalten, welches wir bereits in der Survey verwenden (erst Grundgerüst erstellen, welches anschließend stückweise gefüllt werden kann). Weiterhin erleichtert dieser Ablauf die Verwaltung der Entitäten sowohl auf Frontend-, als auch auf Backend-Seite
